//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
#RE_IN_DE
#pragma define (store)
SignalGenerator : CLASS_PUBLIC
	TYPE
	  CmdClassSvr :
	  (
	    startSignal,
	    stopSignal,
	    resetSignal,
	    setAmplitude,
	    setRefSignal,
	    setPeriodicTime,
	    setSignalTypeRectangle,
	    setSignalTypeSawtooth,
	    setSignalTypeSine,
	    setSignalTypeTriangle,
	    setSignalTypeUserTable,
	    setUserTable,
	    getSignal,
	    getInterfaceVersion
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)

#RE_IN_DE
