//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
  SignalType :
  (
    Rectangle,
    Sawtooth,
    Sine,
    Triangle,
    UserTable
  )$UDINT;
END_TYPE
