//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef UDINT SignalType; 
    #define Rectangle 0
    #define Sawtooth 1
    #define Sine 2
    #define Triangle 3
    #define UserTable 4

