//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh_DATE_LSL 
  {
    CHMETH *pMeth;
    DATE_LSL dData;
    SVRDSC *pDsc;
  } SvrCh_DATE_LSL;

typedef struct CltCh_DATE_LSL 
  {
    struct SvrCh_DATE_LSL *pCh;
    DATE_LSL dData;
    SVRCHCMD *pCmd;
  } CltCh_DATE_LSL;

typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_TIME_LSL 
  {
    CHMETH *pMeth;
    TIME_LSL dData;
    SVRDSC *pDsc;
  } SvrCh_TIME_LSL;

typedef struct CltCh_TIME_LSL 
  {
    struct SvrCh_TIME_LSL *pCh;
    TIME_LSL dData;
    SVRCHCMD *pCmd;
  } CltCh_TIME_LSL;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd_Ram 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Ram *pCmd;
  } CltChCmd_Ram;

typedef struct CltChCmd_System 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    System *pCmd;
  } CltChCmd_System;

typedef struct SvrChCmd_DATE_LSL 
  {
    CMDMETH *pMeth;
    DATE_LSL dData;
    SVRDSC *pDsc;
  } SvrChCmd_DATE_LSL;

